
import java.util.Scanner;

/*Malika Sharma
 *Multiple Choice Quiz 
 *02/10/2019
 *
 */

/**
 *
 * @author VIASVS
 */
public class multipleChoiceFrame extends javax.swing.JFrame {

    /**
     * Creates new form multipleChoiceFrame
     */
    public multipleChoiceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        information = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        option1 = new javax.swing.JLabel();
        option2 = new javax.swing.JLabel();
        option3 = new javax.swing.JLabel();
        option4 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        answer1 = new javax.swing.JTextField();
        option5 = new javax.swing.JLabel();
        option6 = new javax.swing.JLabel();
        option7 = new javax.swing.JLabel();
        option8 = new javax.swing.JLabel();
        answer2 = new javax.swing.JTextField();
        question3 = new javax.swing.JLabel();
        option9 = new javax.swing.JLabel();
        option10 = new javax.swing.JLabel();
        option13 = new javax.swing.JLabel();
        option14 = new javax.swing.JLabel();
        answer3 = new javax.swing.JTextField();
        question4 = new javax.swing.JLabel();
        option15 = new javax.swing.JLabel();
        option16 = new javax.swing.JLabel();
        option17 = new javax.swing.JLabel();
        option18 = new javax.swing.JLabel();
        answer4 = new javax.swing.JTextField();
        question5 = new javax.swing.JLabel();
        option19 = new javax.swing.JLabel();
        option20 = new javax.swing.JLabel();
        option21 = new javax.swing.JLabel();
        option22 = new javax.swing.JLabel();
        answer5 = new javax.swing.JTextField();
        correct = new javax.swing.JLabel();
        incorrect = new javax.swing.JLabel();
        percentage = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        wordDisplay1 = new javax.swing.JLabel();
        wordDisplay2 = new javax.swing.JLabel();
        wordDisplay3 = new javax.swing.JLabel();
        wordDisplay4 = new javax.swing.JLabel();
        wordDisplay5 = new javax.swing.JLabel();
        correctDisplay = new javax.swing.JLabel();
        incorrectDisplay = new javax.swing.JLabel();
        percentDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        tittle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tittle.setText("Constants and Variables Quiz ");

        information.setText("Answer each question and record your answer with the correct NUMBER in the box beside.  ");

        question1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        question1.setText("1.) How many values can a variable store at one time? ");

        option1.setText("1.) 1");

        option2.setText("2.) 2");

        option3.setText("3.) 5");

        option4.setText("4.) 10");

        question2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        question2.setText("2.) Which data type declares a variable that stores a true or false value? ");

        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });

        option5.setText("1.) int");

        option6.setText("2.) char");

        option7.setText("3.) boolean");

        option8.setText("4.) double ");

        question3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        question3.setText("3.) What operator is used for division?");

        option9.setText("1.) *");

        option10.setText("2.) /");

        option13.setText("3.) #");

        option14.setText("4.) %");

        question4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        question4.setText("4.) Which statement is used to make the members of a package accessible to an application? ");

        option15.setText("1.) import");

        option16.setText("2.) static");

        option17.setText("3.) class");

        option18.setText("4.) public");

        question5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        question5.setText("5.) What is the result of the following expression when x is 3576? (x/10)%10 ");

        option19.setText("1.) 6");

        option20.setText("2.) 357");

        option21.setText("3.) 7");

        option22.setText("4.) 76");

        correct.setText("Number of questions answered correctly");

        incorrect.setText("Number of questions answered incorrectly");

        percentage.setText("Percentage of questions answered correctly");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(option13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(option7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(option8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(tittle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(option5)
                                .addGap(18, 18, 18)
                                .addComponent(option6)
                                .addGap(59, 59, 59)
                                .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(wordDisplay2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(option15)
                        .addGap(18, 18, 18)
                        .addComponent(option16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(option17)
                        .addGap(18, 18, 18)
                        .addComponent(option18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(wordDisplay4))
                    .addComponent(question5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(option21)
                        .addGap(18, 18, 18)
                        .addComponent(option22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(incorrect)
                        .addGap(18, 18, 18)
                        .addComponent(incorrectDisplay))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(percentage)
                        .addGap(18, 18, 18)
                        .addComponent(percentDisplay))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question1)
                            .addComponent(question3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(option9)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option14)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(option10)
                                        .addGap(39, 39, 39)
                                        .addComponent(answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109)
                                        .addComponent(wordDisplay3))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(option1)
                                        .addGap(41, 41, 41)
                                        .addComponent(option2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(option3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(option4)))
                                .addGap(47, 47, 47)
                                .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(wordDisplay1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(correct)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(correctDisplay))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(option19)
                                    .addGap(18, 18, 18)
                                    .addComponent(option20)
                                    .addGap(33, 33, 33)
                                    .addComponent(answer5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(111, 111, 111)
                                    .addComponent(wordDisplay5)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(information)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(information)
                        .addGap(19, 19, 19)
                        .addComponent(question1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(option1)
                                .addComponent(option2))
                            .addComponent(wordDisplay1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option3)
                    .addComponent(option4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option7)
                            .addComponent(option8))
                        .addGap(27, 27, 27)
                        .addComponent(question3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option9)
                            .addComponent(option10))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(question2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(option5)
                                            .addComponent(option6)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(wordDisplay2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wordDisplay3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(answer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option13)
                    .addComponent(option14))
                .addGap(27, 27, 27)
                .addComponent(question4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option15)
                    .addComponent(option16))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordDisplay4))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option17)
                    .addComponent(option18))
                .addGap(31, 31, 31)
                .addComponent(question5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(option19)
                                .addComponent(option20))
                            .addComponent(wordDisplay5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option21)
                            .addComponent(option22)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(answer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(submitButton)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correct)
                    .addComponent(correctDisplay))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incorrect)
                    .addComponent(incorrectDisplay))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentage)
                    .addComponent(percentDisplay))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Scanner keyedInput = new Scanner (System.in); 
       double question1 = Double.parseDouble(answer1.getText());
       double question2 = Double.parseDouble(answer2.getText());
       double question3 = Double.parseDouble(answer3.getText());
       double question4 = Double.parseDouble(answer4.getText());
       double question5 = Double.parseDouble(answer5.getText());
       int totalcorrect = 0; 
       int totalincorrect =0; 
       int totalpercent = totalcorrect * 100; 
       totalpercent = totalpercent * 100; 
       totalpercent = Math.round(totalpercent); 
       totalpercent = totalpercent/100; 
       correctDisplay.setText(":" + totalcorrect );
       incorrectDisplay.setText(":"+ totalincorrect); 
       percentDisplay.setText(":" + totalpercent); 
       if (question1==1)
         wordDisplay1.setText("Correct, Well done");
       totalcorrect = totalcorrect + 1; 
        if(question1==2)
        wordDisplay1.setText("Incorrect, try again");
        totalincorrect = totalincorrect + 1; 
        if(question1==3)
        wordDisplay1.setText("Incorrect, try again");
        totalincorrect = totalincorrect + 1; 
       if(question1==4) 
        wordDisplay1.setText("Incorrect, try again"); 
       totalincorrect = totalincorrect + 1; 
       if (question2==1)
         wordDisplay2.setText("Incorrect, try again");
       totalincorrect = totalincorrect + 1; 
         if(question2==2)
        wordDisplay2.setText("Incorrect, try again");
        totalincorrect = totalincorrect + 1; 
        if(question2==3)
        wordDisplay2.setText("Correct,Well done");
        totalcorrect = totalcorrect + 1; 
         if(question2==4) 
        wordDisplay3.setText("Incorrect, try again");
       totalincorrect = totalincorrect + 1; 
       if (question3==1) 
         wordDisplay3.setText("Incorrect, try again"); 
       totalincorrect = totalincorrect + 1; 
        if(question3==2)  
        wordDisplay3.setText("Correct, Well done"); 
        totalcorrect = totalcorrect + 1; 
         if(question3==3)
        wordDisplay3.setText("Incorrect, try again"); 
        totalincorrect = totalincorrect + 1; 
         if(question3==4) 
        wordDisplay3.setText("Incorrect, try again");
        totalincorrect = totalincorrect + 1; 
        if (question4==1) 
         wordDisplay4.setText("Correct, Well done"); 
        totalcorrect = totalcorrect + 1; 
         if(question4==2)
        wordDisplay4.setText("Incorrect, try again");
        totalincorrect = totalincorrect + 1; 
         if(question4==3)
        wordDisplay4.setText("Incorrect, try again ");
        totalincorrect = totalincorrect + 1; 
        if(question4==4) 
        wordDisplay4.setText("Incorrect, try again");
        totalincorrect = totalincorrect + 1; 
        if (question5==1) 
         wordDisplay5.setText("Incorrect, try again");
        totalincorrect = totalincorrect + 1; 
        if(question5==2)  
        wordDisplay5.setText("Incorrect, try again");
        totalincorrect = totalincorrect + 1; 
       if(question5==3)
       wordDisplay5.setText("Correct, Well done!");
       totalcorrect = totalcorrect + 1; 
         if(question5==4)
         wordDisplay5.setText("Incorrect, try again");
       totalincorrect = totalincorrect + 1; 
       correctDisplay.setText(String.valueOf(totalcorrect)); 
       incorrectDisplay.setText(String.valueOf(totalincorrect)); 
       percentDisplay.setText(String.valueOf(totalpercent)); 
         
    
         
        
        
        
         
            
        
        
        
        
           
               
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multipleChoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multipleChoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multipleChoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multipleChoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multipleChoiceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer1;
    private javax.swing.JTextField answer2;
    private javax.swing.JTextField answer3;
    private javax.swing.JTextField answer4;
    private javax.swing.JTextField answer5;
    private javax.swing.JLabel correct;
    private javax.swing.JLabel correctDisplay;
    private javax.swing.JLabel incorrect;
    private javax.swing.JLabel incorrectDisplay;
    private javax.swing.JLabel information;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel option1;
    private javax.swing.JLabel option10;
    private javax.swing.JLabel option13;
    private javax.swing.JLabel option14;
    private javax.swing.JLabel option15;
    private javax.swing.JLabel option16;
    private javax.swing.JLabel option17;
    private javax.swing.JLabel option18;
    private javax.swing.JLabel option19;
    private javax.swing.JLabel option2;
    private javax.swing.JLabel option20;
    private javax.swing.JLabel option21;
    private javax.swing.JLabel option22;
    private javax.swing.JLabel option3;
    private javax.swing.JLabel option4;
    private javax.swing.JLabel option5;
    private javax.swing.JLabel option6;
    private javax.swing.JLabel option7;
    private javax.swing.JLabel option8;
    private javax.swing.JLabel option9;
    private javax.swing.JLabel percentDisplay;
    private javax.swing.JLabel percentage;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel tittle;
    private javax.swing.JLabel wordDisplay1;
    private javax.swing.JLabel wordDisplay2;
    private javax.swing.JLabel wordDisplay3;
    private javax.swing.JLabel wordDisplay4;
    private javax.swing.JLabel wordDisplay5;
    // End of variables declaration//GEN-END:variables
}
